<?php

namespace Database\Seeders;

use App\Models\Staff;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
    //     $strings = array(
    //         'MALE',
    //         'FEMALE',
    //     );

    //     $cTypes = array(
    //         'CDD',
    //         'CDI',
    //         'TEMPORAIRE'
    //     );

    //     $faker = \Faker\Factory::create();
    //     for ($i = 0; $i < 10; $i++) {
    //         $typeIndex = array_rand($strings);
    //         $cTypeIndex = array_rand($cTypes);
    //         Staff::create([
    //             'statut' => rand(0, 1),
    //             'lastname' => $faker->lastName,
    //             'firstname' => $faker->firstName,
    //             'email' => $faker->email,
    //             'date_card_validity' => '2025-12-31',
    //             'phone' => $faker->phoneNumber,
    //             'phone_2' => $faker->phoneNumber,
    //             'father_name' => $faker->firstNameMale,
    //             'father_phone' => $faker->lastName . ' ' . $faker->phoneNumber,
    //             'mother_name' => $faker->lastName . ' ' . $faker->firstNameMale,
    //             'birthday' => '1990-01-01',
    //             'place_birth' => 'Yaoundé',
    //             'profession' => 'Doctor',
    //             'gender' => $strings[$typeIndex],
    //             'contract_type' => $cTypes[$cTypeIndex],
    //             'marital_status' => 'Married',
    //             'position' => 'Head of Department',
    //             'num_children' => 2,
    //             'open_close' => 0,
    //             'city_id' => 1,
    //             'country_id' => 1,
    //             'neighborhood' => $faker->address,
    //             'attachment_file' => $faker->filePath("tmp/file.pdf")
    //         ]);
    //     }
    
    DB::table('staffs')->insert([
            [   
                'id' => 1,
                'lastname' => 'MONGO',
                'firstname' => 'SALOMON',
                'email' => 'infoservice@gmail.com',
                'date_card_validity' => '2021-02-27',
                'phone' => '012478956',
                'father_name' => 'N/A',
                'birthday' => '2021-02-06',
                'place_birth' => 'YAOUNDE',
                'profession' => 'INFORMATICIEN',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'MARIÉ(E)',
                'num_children' => 2,
                'phone_2' => '655021489',
                'position' => 'PDG',
                'statut' => 1,
                'open_close' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => '',
                'attachment_file' => 'N/A'
            ],
            [   
                'id' => 2,
                'lastname' => 'ADAMOU',
                'firstname' => 'MBEN',
                'email' => 'sga@infoservicesh2.com',
                'date_card_validity' => null,
                'phone' => '',
                'father_name' => 'MBEN ADAMOU',
                'birthday' => null,
                'place_birth' => 'YAOUNDE',
                'profession' => 'POSTULANT',
                'gender' => 'FEMALE',
                'contract_type' => 'TEMPORAIRE',
                'marital_status' => 'CELIBATAIRE',
                'num_children' => 2,
                'phone_2' => '6944051020',
                'position' => null,
                'statut' => 0,
                'open_close' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'YAOUNDE',
                'attachment_file' => 'N/A'
            ],
        ]);
         DB::table('staffs')->insert([   [
                'id' => 3,
                'lastname' => 'MANGA MEDZOA',
                'firstname' => 'ELODIE CHANTAL',
                'email' => 'elodiemanga987@gmail.com',
                'date_card_validity' => NULL,
                'phone' => '101277170',
                'phone_2' => '698206743',
                'father_name' => 'MEDZOA ANDRE CLAVER',
                'father_phone' => 'N/A',
                'mother_name' => 'NKOGO ALPHONSINE BEATRICE',
                'birthday' => '1993-10-02',
                'place_birth' => 'YAOUNDE',
                'profession' => 'ASSISTANTE ADMINISTRATIVE',
                'gender' => 'FEMALE',
                'contract_type' => 'CDI',
                'marital_status' => 'CELIBATAIRE',
                'position' => 'ASSISTANTE ADMINISTRATIVE',
                'num_children' => 1,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [
                'id' => 4,
                'lastname' => 'MVOGO ENANI',
                'firstname' => 'LEOPOLD',
                'email' => 'exemple2@gmail.com',
                'date_card_validity' => '2022-02-04',
                'phone' => '114827930',
                'phone_2' => '697447862',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'NNOMO CATHERINE',
                'birthday' => '1971-01-12',
                'place_birth' => 'YAOUNDE',
                'profession' => 'AGENT DE LIAISON',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'MARIÉ(E)',
                'position' => 'N/A',
                'num_children' => 1,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [   
                'id' => 19,
                'lastname' => 'NGO NDENGUE',
                'firstname' => 'VIVIANE',
                'email' => 'exemple3@gmail.com',
                'date_card_validity' => NULL,
                'phone' => 'N/A',
                'phone_2' => '694477512',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => NULL,
                'place_birth' => NULL,
                'profession' => 'SECRETAIRE ADMINISTRATIVE',
                'gender' => 'FEMALE',
                'contract_type' => 'CDI',
                'marital_status' => 'MARIÉ(E)',
                'position' => 'SECRETAIRE ADMINISTRATIF',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [
                'id' => 8,
                'lastname' => 'FEUZEU FEUGANG',
                'firstname' => 'SIMPLICE',
                'email' => 'tsfeuzeu2000@yahoo.fr',
                'date_card_validity' => '2022-02-08',
                'phone' => 'N/A',
                'phone_2' => '676806484',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => '2022-02-08',
                'place_birth' => '----',
                'profession' => 'INGENIEUR DE GENIE CIVIL',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],[ 
                'id' => 9,
                'lastname' => 'M. BOUBAKAR',
                'firstname' => 'TOURE',
                'email' => 'petiasse@yahoo.fr',
                'date_card_validity' => NULL,
                'phone' => '',
                'phone_2' => '699817274',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => NULL,
                'place_birth' => NULL,
                'profession' => 'N/A',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [   
                'id' => 10,
                'lastname' => 'M. PEMAN GEOMBANG',
                'firstname' => 'Just-Fourier',
                'email' => 'just-fourier@hotmail.com',
                'date_card_validity' => NULL,
                'phone' => '654803191',
                'phone_2' => '698552623',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => NULL,
                'place_birth' => 'N/A',
                'profession' => 'N/A',
                'gender' => 'MALE',
                'contract_type' => 'TEMPORAIRE',
                'marital_status' => 'N/A',
                'position' => 'RESPONSABLE DE LA PLANIFICATION',
                'num_children' => 2,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            ]);
          DB::table('staffs')->insert([
              
            [   
                'id' => 11,
                'lastname' => 'M. WAIMO',
                'firstname' => 'FELTOING',
                'email' => 'waimofeltoing110@gmail.com',
                'date_card_validity' => '2022-02-08',
                'phone' => '699582038',
                'phone_2' => '699582038',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => '2022-02-08',
                'place_birth' => NULL,
                'profession' => 'N/A',
                'gender' => 'FEMALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [   
                'id' => 12,
                'lastname' => 'EKOUTA',
                'firstname' => 'Dieudonné',
                'email' => 'd_ekouta@yahoo.fr',
                'date_card_validity' => '2022-02-08',
                'phone' => '699582038',
                'phone_2' => '699999652',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => '2022-02-08',
                'place_birth' => NULL,
                'profession' => 'N/A',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [   
                'id' => 13,
                'lastname' => 'ZOUA',
                'firstname' => 'Lucas',
                'email' => 'lucaszoua@yahoo.fr',
                'date_card_validity' => '2022-02-08',
                'phone' => '699582038',
                'phone_2' => '699947501',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => '2022-02-08',
                'place_birth' => NULL,
                'profession' => 'N/A',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [   
                'id' => 14,
                'lastname' => 'M.YEYUNG GHOGOMU',
                'firstname' => 'MBIMINA',
                'email' => 'yeyungmb@yahoo.co.uk',
                'date_card_validity' => '2022-02-08',
                'phone' => '677622199',
                'phone_2' => '677622199',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => '2022-02-08',
                'place_birth' =>NULL,
                'profession' => 'N/A',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [   
                'id' => 15,
                'lastname' => 'AMADOU',
                'firstname' => 'TEJANI',
                'email' => 'tejamadou@yahoo.fr',
                'date_card_validity' => '2022-02-08',
                'phone' => '699582038',
                'phone_2' => '699822859',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => NULL,
                'place_birth' => NULL,
                'profession' => 'N/A',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
            [   
                'id' => 16,
                'lastname' => 'NGBWA BITA',
                'firstname' => 'Victor',
                'email' => 'ngbwave@yahoo.fr',
                'date_card_validity' => '2022-02-08',
                'phone' => '699582038',
                'phone_2' => '699608701',
                'father_name' => 'N/A',
                'father_phone' => 'N/A',
                'mother_name' => 'N/A',
                'birthday' => NULL,
                'place_birth' => NULL,
                'profession' => 'N/A',
                'gender' => 'MALE',
                'contract_type' => 'CDI',
                'marital_status' => 'N/A',
                'position' => 'REPRESENTANT REGIONAL',
                'num_children' => 0,
                'city_id' => 1,
                'country_id' => 1,
                'neighborhood' => 'N/A',
                'attachment_file' => 'N/A',
                'statut' => 0,
                'open_close' => 0,
            ],
        ]);
     }
    
}
